### PR TITLE
🚧  move to begin

### LINKED ISSUE #8: Move away from Vercel
Turns out Vercel doesn't want to sponsor our little app, because it uses a serverless function. I'm not willing to pay $20/month for it just to stay at Vercel.

I'm open to suggestions. I really enjoyed Netlify lately, but I can also deploy it to @BeginCI, or something else? Cloudflare worker maybe? I'm open to suggestions

### PR DESCRIPTION
**Pull request by gr2m**
fixes https://github.com/squash-commit-app/squash-commit-app/issues/8

More info in: https://begin.com/

### CODE REVIEW

**Comment by gr2m** [comment]
@oscard0m sorry I removed the TypeScript to simplify the app and deployment, I hope that's okay with you.

**Comment by gr2m** [comment]
I don't know how to deploy the app from a branch other then `main`, see my question here: https://github.com/squash-commit-app/squash-commit-app/issues/8#issuecomment-848362886

So I'm going to merge this and see how it goes 🤪

**Comment by oscard0m** [comment]
> @oscard0m sorry I removed the TypeScript to simplify the app and deployment, I hope that's okay with you.

No problem, with JS

> @oscard0m sorry I removed the TypeScript to simplify the app and deployment, I hope that's okay with you.

With JSDocs I hope we catch most of the problems

**Review by oscard0m — COMMENTED** [review]
LGTM

**Pull request merged**
